vim.opt.shortmess:append 'I'
require('taylor.keymaps')
require('taylor.gruvbox')
require('taylor.telescope')
require('taylor.treesitter')
require('taylor.lsp-zero')
require('taylor.lspconfig')
require('taylor.vimtex')
require('taylor.neogit')
require('taylor.tree')
require('taylor.feline')
